# Part 2
# Section 10: Numpy

Numpy is a Python library that allows you to build multidimensional arrays. Operations with Numpy tend to be faster compared to other Python structures because 30% of the library is written in C, among other aspects.

## 10.1 - Arrays

### Syntax

```python
import numpy as np
arr = np.array([1, 2, 3, 4, 5]) # 1d array
```

### Some array attributes

| Attribute | Returns | Description |
| :-- | :-- | :-- |
| ndarray.ndim | int | number of dimensions (axes) |
| ndarray.shape | tuple | number of elements in each dimension |
| ndarray.size | int | number of elements |
| ndarray.dtype | dtype | data type of the elements |

**Note:**
- `np.array(iterable)` is a function that returns an ndarray object.
- We can create arrays with as many dimensions as needed.

In [4]:
import numpy as np

In [5]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
b = np.array(a)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
type(b)

numpy.ndarray

In [12]:
b.ndim

1

In [15]:
b.dtype

dtype('int32')

In [17]:
c = [[1, 2, 3], [10, 11, 12]]
d = np.array(c)
d

array([[ 1,  2,  3],
       [10, 11, 12]])

In [18]:
d.ndim

2

In [20]:
d.shape

(2, 3)

In [21]:
d.size

6

In [33]:
e = [[[1, 2, 3],
     [10, 11, 12]],

     [[1,10.1, 3],
     [10, 11, 12]]]
f = np.array(e)
f

array([[[ 1. ,  2. ,  3. ],
        [10. , 11. , 12. ]],

       [[ 1. , 10.1,  3. ],
        [10. , 11. , 12. ]]])

In [34]:
f.dtype

dtype('float64')

## 10.2 - Math functions

### Trigonometric functions

| Function | Description |
| :-- | :-- |
| sin(x) | Sine |
| cos(x) | Cosine |
| tan(x) | Tangent |
| arcsin(x) | Arcsine |
| arccos(x) | Arccosine |
| arctan(x) | Arctangent |
| sinh(x) | Hyperbolic sine |

### Exponential and logarithmic functions

| Function | Description |
| :-- | :-- |
| exp(x) | Exponential |
| log(x) | Natural logarithm |
| log10(x) | Base 10 logarithm |
| sqrt(x) | Square root |

### Constants

| Constant | Description |
| :-- | :-- |
| np.pi | $\pi$ = 3.141592... |
| np.e | $e$ = 2.7182... |
| np.nan | Representation of a non-numeric value (not a number) |
| np.inf | Representation of infinity |

**Note:** You can find more information about mathematical functions in the [Numpy documentation](https://numpy.org/doc/stable/reference/routines.math.html).

In [43]:
import math

from numpy import cos, sin
from numpy import pi, nan



In [39]:
cos(0)

1.0

In [46]:
type(nan)

float

In [51]:
a = np.array(
    [1, 2, 3, nan]
)

In [53]:
a.dtype

dtype('float64')

In [55]:
a ** 2

array([ 1.,  4.,  9., nan])

In [57]:
cos(pi/2)

6.123233995736766e-17

## 10.3 - Array Creation

### Functions for array creation

| Function | Description |
| :-- | :-- |
| np.zeros(shape) | array filled with zeros |
| np.ones(shape) | array filled with ones |
| np.eye(dimensão) | identity matrix |
| np.arange(start, stop, step) | creates a one-dimensional array |
| np.linspace(start, stop, quantity) | creates a one-dimensional array |
| np.vstack([*arrays*]) and hstack([*arrays*]) | adds elements from one or more arrays |

### Methods for resizing arrays:

 | Method | Description |
| :-- | :-- |
|reshape(new_shape) | returns an array with the specified shape|
|resize(new_shape) | modifies the shape of the array being applied|


**Note**
<pre>Pay attention to which methods modify the array and which return a new array </pre>
<pre>Arrays do not have dynamic size like lists. But we can "steal" and modify the size of an array by stacking them (a new object will be generated). </pre>

In [58]:
import numpy as np

In [59]:
a = np.zeros(20)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [64]:
a[2] += 1

In [65]:
a

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [67]:
b = np.eye(10)

In [68]:
b

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [69]:
b.shape

(10, 10)

In [77]:
step = 0.5
c = np.arange(0, 20+step, step)

In [78]:
c

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [72]:
c.size

40

In [74]:
d = np.linspace(0, 30, 12)

In [75]:
d

array([ 0.        ,  2.72727273,  5.45454545,  8.18181818, 10.90909091,
       13.63636364, 16.36363636, 19.09090909, 21.81818182, 24.54545455,
       27.27272727, 30.        ])

In [80]:
e = np.ones(20)
e.shape

(20,)

In [81]:
e.reshape(4, 5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [88]:
f = d.reshape(3, 4)

In [87]:
d.shape

(12,)

In [90]:
f.shape

(3, 4)

In [93]:
d.resize(3, 4)

In [95]:
d.shape

(3, 4)

In [100]:
d

array([[ 0.        ,  2.72727273,  5.45454545,  8.18181818],
       [10.90909091, 13.63636364, 16.36363636, 19.09090909],
       [21.81818182, 24.54545455, 27.27272727, 30.        ]])

In [107]:
h

array([[1, 2, 3, 6],
       [4, 5, 6, 9]])

In [104]:
h = np.array([[1, 2, 3, 6],
              [4, 5, 6, 9]])
h.shape

(2, 4)

In [105]:
g = np.vstack([d, h])

In [106]:
g.shape

(5, 4)

In [108]:
g

array([[ 0.        ,  2.72727273,  5.45454545,  8.18181818],
       [10.90909091, 13.63636364, 16.36363636, 19.09090909],
       [21.81818182, 24.54545455, 27.27272727, 30.        ],
       [ 1.        ,  2.        ,  3.        ,  6.        ],
       [ 4.        ,  5.        ,  6.        ,  9.        ]])

In [110]:
h

array([[1, 2, 3, 6],
       [4, 5, 6, 9]])

## 10.4 - Basic Operations with Arrays

Arrays in numpy have many (MANY) functionalities. They can behave like simple data structures, such as vectors or even matrices, depending on how we manipulate them. In this lesson, we will see the basic operations, those that make arrays behave like data structures.

**Basic operations and how they behave**
- Arrays accept basic operations $+$, $-$, $\times$, $\div$ and execute them element-wise, so arrays must have exactly the same shape.
- Arrays accept basic operations between an array and a number (float or int). It will execute the operation between the number and each element of the array.
- Boolean operations are also accepted and return an array filled with booleans.

**Note**
<pre>Later on, we will see vector and matrix operations with arrays. </pre>

In [13]:
import numpy as np

In [31]:
arr_1 = np.linspace(1, 10, 10).reshape(2, 5)
arr_2 = np.linspace(1, 100, 10).reshape(2, 5)


In [33]:
8 * arr_1

array([[ 8., 16., 24., 32., 40.],
       [48., 56., 64., 72., 80.]])

In [57]:
a = np.array([1, 2, 3])
b = np.array([1, 5, 3])

a == b

array([ True, False,  True])

## 10.5 - Numpy Memory Management

Remember that the numpy array is not dynamic. Also, be careful with objects when copying, manipulating, and pasting.

#### Copying an array
| Method | Description |
| :-- | :-- |
| .copy() | makes a copy (deep copy) of the array. Be careful! The equal sign does not execute this function |

#### Property
| Method | Description |
| :-- | :-- |
| .base | Returns the base array that was used to create the current array |

**Note**
<pre>We can use the logical operator `is` to check if we have a new object. </pre>

In [1]:
import numpy as np

In [4]:
np.may_share_memory

<function numpy.may_share_memory>

In [8]:
arr_1 = np.linspace(1, 10 , 10)

In [10]:
arr_1.reshape(2, 5)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [11]:
arr_1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
arr_2 = arr_1.reshape(2, 5)

In [19]:
hex(id(arr_2.base))

'0x1c75f8ecb70'

In [20]:
hex(id(arr_1))

'0x1c75f8ecc30'

In [21]:
np.may_share_memory(arr_1, arr_2)

True

In [27]:
arr_1.nbytes

80

## 10.6 Statistical Methods for Arrays

| Method | Description |
| :-- | :-- |
| max(axis=None) | Returns the maximum value |
| min(axis=None) | Returns the minimum value |
| argmax(axis=None) | Returns the index of the maximum value |
| argmin(axis=None) | Returns the index of the minimum value |
| sum(axis=None) | Returns the sum of the array elements |
| cumsum(axis=None) | Returns an array with the cumulative sum of the values |
| prod(axis=None) | Returns the product of the array elements |
| cumprod(axis=None) | Returns the cumulative product of the array elements |
| mean(axis=None) | Returns the mean of the array elements |
| var(axis=None) | Returns the variance of the array |
| std(axis=None) | Returns the standard deviation of the array |

**Note**
<pre>When the axis option is used, we perform the operation along the specified axis. </pre>

In [37]:
arr_1.cumsum()

array([ 1.,  3.,  6., 10., 15., 21., 28., 36., 45., 55.])

## 10.7 Array Indexing and Slicing

Similar to what we did with lists, we can slice arrays.

| Syntax | Description |
| :-- | :-- |
| [i] | for 1 dimension works as in lists |
| [:i] | displays an array from index 0 to one before i |
| [i:] | displays an array from index i to the last index |
| [::i] | displays all elements varying from i to i |
| [::-i] | displays the sequence of elements from back to front varying from i to i |
| [a:b:c] | start, end, step |
| [i,j] | to display an element of a matrix |
| [i,a:b] | returns a slice of row i with elements from columns a to b |
| [n,i,j] | another dimension, row, column |

**Note**
<pre>There are more sophisticated operations for slicing, known as fancy indexing.</pre>

## 10.8 - Matrices in Numpy

Numpy arrays can be directly interpreted as matrices. For this, we need to use the right functions!

#### Properties
| Properties | Description |
| :-- | :-- |
| .T | Transposed matrix |

#### Functions
| Functions | Description |
| :-- | :-- |
| np.transpose(A) | Returns the transposed matrix of A |
| np.linalg.det(A) | Returns the determinant of matrix A |
| np.matmul(A, B) or @ | Returns the matrix multiplication between A and B. |

**Note**
<pre>linalg is a separate package from numpy. It has many functionalities that we will explore in the scipy chapter.</pre>
<pre>Numpy also has an object np.matrix, which allows us to perform matrix operations in a simpler way. I personally prefer using arrays.</pre>

In [1]:
import numpy as np

In [4]:
a = np.linspace(1, 10, 10).reshape(2, 5)
b = np.linspace(11, 20, 10).reshape(5, 2)

In [54]:
e = np.linspace(1, 1.5, 9).reshape(3, 3)

In [55]:
d

array([[1.    , 1.0625, 1.125 ],
       [1.1875, 1.25  , 1.3125],
       [1.375 , 1.4375, 1.5   ]])

In [56]:
np.linalg.det(e)

0.0

In [19]:
np.cross(a, b)

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [14]:
b.transpose()

array([[11., 13., 15., 17., 19.],
       [12., 14., 16., 18., 20.]])

In [16]:
b.T

array([[11., 13., 15., 17., 19.],
       [12., 14., 16., 18., 20.]])

In [30]:
c = np.linspace(1, 3, 3)

In [31]:
np.cross(c, c)

array([0., 0., 0.])

## 10.9 - Vectors

#### Functions
| Functions | Description |
| :-- | :-- |
| np.cross(a, b) | Cross product (the array must be a vector with 2 or 3 elements) |
| np.dot(a, b) or @ | Dot product (scalar product) |
| np.linalg.norm(a) | Returns the norm of vector a |

#### Cross Product
The cross product between two vectors results in a third vector orthogonal to the other two.

$$ \vec{a} \times \vec{b} = | a | \cdot | b | \cdot \sin(\theta) \cdot \vec{n}  =  \begin{bmatrix}
   \vec{i} & \vec{j} & \vec{k} \\
   a_x & a_y & a_z \\
   b_x & b_y & b_z
  \end{bmatrix} $$

#### Dot Product
The dot product between two vectors yields a real number. Geometrically, the dot product provides the projection of vector $\vec{a}$ onto $\vec{b}$ if the latter has unit length.

$$ \vec{a} \cdot \vec{b} = (a_x \cdot b_x + a_y \cdot b_y + a_z \cdot b_z) =  | a | \cdot | b | \cdot \cos(\theta)$$

<pre>The linalg is a separate package from numpy. It has other functionalities that we will explore in the scipy chapter.</pre>

In [36]:
np.matmul(c, c)

14.0

# Exercises

## E10.1 - 
Create a $2 \times  2$ matrix fully filled with $\pi$.

In [5]:
import numpy as np

m = np.array([[np.pi, np.pi],
              [np.pi, np.pi]])

In [6]:
m

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

## E10.2 - 
Create a $10 \times  10$ matrix fully filled with $\pi$.

In [11]:
m = np.ones(100).reshape(10, 10) * np.pi
m

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.1415926

## E10.3 -
Create a $2 \times  10$ matrix where both rows contain arrays with integers from 1 to 10.

Change the last number of the matrix from 10 to 100.

In [12]:
import numpy as np

In [32]:
a = np.arange(1, 11, 1)

b = np.vstack([a, a])

In [33]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [37]:
b[1, 9] = 100

In [38]:
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9, 100]])

## E10.4 -
Given an array of integers ranging from 0 to 100, return the standard deviation and variance of this array.

In [39]:
import numpy as np

In [45]:
a = np.arange(0, 101, 1)
a.min()

0

## E10.5 -
Generate a $3 \times 10$ matrix with random numbers. Then, extract an array with the last three numbers from the second row.

<br/>

Hint:

Use the function below to generate an array with random numbers
```python
>>> np.random.rand(3, 10)
```

In [46]:
import numpy as np

In [47]:
m = np.random.rand(3, 10)
m

array([[0.32470555, 0.43836869, 0.76355356, 0.11373676, 0.15918102,
        0.80368824, 0.61012429, 0.28376739, 0.30488679, 0.1910903 ],
       [0.68835688, 0.9508969 , 0.67019275, 0.52330445, 0.61895698,
        0.63219067, 0.55123872, 0.26562141, 0.5501472 , 0.70420808],
       [0.93357046, 0.01908056, 0.53493673, 0.70948041, 0.3311262 ,
        0.37121507, 0.14426469, 0.44893492, 0.56031485, 0.87626918]])

In [58]:
m[1, 7::]

array([0.26562141, 0.5501472 , 0.70420808])